FROM ubuntu:18.04
RUN apt-get update && apt-get install -yq build-essential autoconf libnetcdf-dev libxml2-dev libproj-dev subversion valgrind dos2unix gawk

COPY atlantisCode/v6645/atlantis /app/atlantis
COPY atlantisCode/v6645/.svn /app/.svn

RUN gcc -v

RUN cd /app/atlantis && aclocal && autoheader && autoconf && automake -a && ./configure && make && make install

WORKDIR /app/model

CMD ./RunAtlantis_6645.sh
