---
title: "Supplement: Capturing the Regional Signature: Calibration, Sensitivity, and Path Dependence in the NEUSv2 Atlantis Model"
author: "Joseph C Caracappa, Andrew Beet, Robert Gamble, Scott Large"
date: "`r Sys.Date()`"
output: 
  bookdown::word_document2:
    toc: no
    number_sections: yes
    reference_docx: null # Optional: see below
# header-includes: 
#   - \usepackage{amsmath} 
#   - \usepackage[section]{placeins} 
bibliography: fishing_sensitivity_refs.bib
csl: ecological-modelling.csl 
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
tab.dir = 'Z:/Shared_Data/fishing_sensitivity_manuscript/tables/'
```


```{r calib-tab, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Summary of calibration status of NEUSv2 functional groups."}
  fgs = read.csv(here::here('currentVersion','neus_groups.csv')) |> 
  dplyr::select(Code,LongName)
  stats= read.csv(paste0(tab.dir,'table_1_species_metrics.csv')) |> 
    dplyr::left_join(fgs) |> 
    dplyr::select(Code,LongName, Stable, Reasonable, Relative_Change, Min_Target_q, Max_Target_q,Average_Biomass,Average_Catch,F_rate)|> 
    dplyr::mutate(Min_Target_q = signif(Min_Target_q,2),
                  Max_Target_q = signif(Max_Target_q,2),
                  Stable = ifelse(Stable == T,"T","F"),
                  Reasonable = ifelse(Reasonable == T,"T","F")) |> 
    dplyr::rename(
    `Species.Name` = LongName,
    `Species.Code` = Code,
    `Relative.Change` = Relative_Change,
    `Target.Min` = Min_Target_q,
    `Target.Max` = Max_Target_q,
    `Average.Biomass` = Average_Biomass,
    `Average.Catch` = Average_Catch,
    `F.Rate` = F_rate
  ) |> 
    dplyr::arrange(Species.Code)
    
  stats |> 
    flextable::flextable() |> 
    flextable::colformat_double(digits = 2) |> 
    flextable::separate_header(split = "\\.") |>
    flextable::align(align = "center", part = "all") |> 
    flextable::valign(valign = "bottom", part = "header") |>
    flextable::padding(padding = 1, part = "all") |>  
    flextable::fontsize(size = 9, part = "all") |>  
    flextable::autofit() |> 
    flextable::set_table_properties(layout = "autofit", width = 1)
```


