---
title: "Testing Steps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is used to document steps made towards a new version/subversion

* reason for change - Developers initials - name of local filename changed

## Primary Production and Benthic Community Update

* JC: 02-13-2020
* Reduces magnitude of Diatom (PL) bloom and stabilizes closer to initial biomass
    + Reduce mum_PL
    + Increase predation on PL by Meiobenthos (BO) in sediment (reduces sediment accumulation)
    + Decrease cannibalism of BO
* Slight increase in longevity of scallops (SCA) and Lobseter (LOB)
    + Decreased cannibalism in LOB (and other benthic carnivores)
    + Increase grazing of benthic filter feeders (CLA, SCA, QHG, BFF) on PL and decrease consumption of refractory detritus (DR)
* Affects: at_biology.prm

## Planktivores Update

* RG: 04-22-2020
* Fixed a recruitment issue with Herring related to a bug in the code if it happens too late in the year
    + This is a fudge, and needs to be reverted once the bug is fixed in Atlantis
* Fixed the lower trophic levels that herring and mackerel rely on, to persist at levels at which starvation isn't an issue
    + Increased the initial biomasses of phytoplankton and zooplankton groups
    + Tweaked the pprey values between the lower trophic levels to keep species from being preyed upon enough to crash
* Increased initial biomass values for Mackerel and Herring
* Increased recruits per year for Mackerel and Herring
* Increased assimilation efficiency for Mackerel and Herring
    + Mackerel persists at resonable levels
    + Herring still collapses at time step 51 with normal fishing
* Affects: at_biology_test.prm, at_run_WIN_test.prm
