---
title: "Testing Steps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file is used to document steps made towards a new version/subversion

* reason for change - Developers initials - name of local filename changed

## Primary Production and Benthic Community Update

* JC: 02-13-2020
* Reduces magnitude of Diatom (PL) bloom and stabilizes closer to initial biomass
    + Reduce mum_PL
    + Increase predation on PL by Meiobenthos (BO) in sediment (reduces sediment accumulation)
    + Decrease cannibalism of BO
* Slight increase in longevity of scallops (SCA) and Lobseter (LOB)
    + Decreased cannibalism in LOB (and other benthic carnivores)
    + Increase grazing of benthic filter feeders (CLA, SCA, QHG, BFF) on PL and decrease consumption of refractory detritus (DR)
* Affects: at_biology.prm

## Planktivores Update

* RG: 04-22-2020
* Fixed a recruitment issue with Herring related to a bug in the code if it happens too late in the year
    + This is a fudge, and needs to be reverted once the bug is fixed in Atlantis
* Fixed the lower trophic levels that herring and mackerel rely on, to persist at levels at which starvation isn't an issue
    + Increased the initial biomasses of phytoplankton and zooplankton groups
    + Tweaked the pprey values between the lower trophic levels to keep species from being preyed upon enough to crash
* Increased initial biomass values for Mackerel and Herring
* Increased recruits per year for Mackerel and Herring
* Increased assimilation efficiency for Mackerel and Herring
    + Mackerel persists at resonable levels
    + Herring still collapses at time step 51 with normal fishing
* Changed the age structure of the catch for Mackerel and Herring to prevent overfishing at lower age classes
* Affects: at_biology_test.prm, at_run_test.prm, at_harvest_test.prm

* RG: 4-26-2020
* Tested the run with the COBALT forcing for lower trophic levels
    + Herring persisted at full fishing levels - but still drop after the 50th time step, not to as great a magnitude as previously
    + Increased herring recruit numbers
    + Mackerel persist and probably need to have biological parameters reduced a bit to constrain growth

## Mackerel and Menhaden Update

* RG: 05-06-2020
* Increased Mackerel recruits
    + Mackerel persists to end now, though at perhaps too high a biomass - will need to be tuned further after next forcing files
* Increased Menhaden recruits, assimilation efficiency and modified age structure of the catch to allow larger age classes to persist better
    + Menhaden persists almost to end now
    
## Menhaden Update
 
* RG: 05-14-2020
* Increased Menhaden recruits
* Increased growth on Menhaden's first 3 age classes
+ Menhaden persists to end now and at about half of Mackerel's biomass

## Benthic Community Update

* RG: 06-15-2020
* Increased Initial Biomass for Lobster and Red Crab
* Decreased predation between and cannibalism by Lobster and Red Crab
* Increased growth on Macroalgae - important food source for Benthic Grazers
* Decreased predation by LOB, RCB, BC, BMS (other crabs) on Benthic Grazers
* Increased growth on BG
* Increased assimilation efficiencies for BG, LOB, RCB
+ All benthic species persist to the end now.  Clams appear to have too high a biomass, so the next step will be to try to bring them down a bit and finish off the Benthic Community Persists story on the Jira board.

## Rerun for new plankton levels (ATLNTS-107)
* RG: 06-25-2020
* RCB, LOB, BMS and MEN crashed at the end of the run where they used to persist
* All changes made to at_biology.prm file
* Modified MEN assimilation efficiencies
* Increased growth rates for LOB, RCB and BMS
+ All previously persisting species continue to persist

## Top Commercial and Recerational Species Persistence (ATLNTS-3)
 * RG: 07-17-2020
 * SUF: Increased assimilation efficiency and number of recruits
 * WPF: Increased number of recruits and growth rate
 * TYL: Increased number of recruits
 * DRM: Increased number of recruits
 * ZG: Reduced predation on, increased assimilation efficiency, increased growth
 * MEN: Increased assimilation efficiency and number of recruits

## Retune previously tuned species (ATLNTS-155)
 * RG: 07-17-2020
 * BC: Increased growth rate
 * LOB: Increased growth rate

## Migratory species move in and out of model as expected (ATLNTS-8)
 * RG: 09-21-2020
 * Migratory species were modified to have their leaving the model domain on day 1 and returning after a length of time equal to how long they were originally parameterized for
 * All migratory species now persist to end of the model run in both juvenile and adult age classes
 * Task not closed yet on Jira because the time period the species leave are not biologically accurate

## Retune previously tuned species (ATLNTS-155)
 * RG: 10-04-2020
 * Lowered TUN, BFT, and BIL C and mum parameters - still higher than most other fish groups.
 * Lowered growth rates outside the model
 * Lowered survivorship outside the model to take into account predation on juveniles and fishing.
 * TUN and BIL now persist at reasonable levels.  BFT collapses and comes back eventually due to lowered fishing & constant recruitment

## Retune previously tuned species (ATLNTS-155)
 * RG: 10-18-2020
 * Increased BFT C and mum parameters
 * Increased growth rates outside the model
 * Increased survivorship outside the model to take into account predation on juveniles and fishing.
 * BFT currently crashes in the middle of the run but return near the end to normal levels.  Since they aren't a huge player in the model, I am calling this 'done' for now.
 
## Retune Charismatics and Benthic Groups (ATLNTS-155)
 * RG: 10-30-2020
 * Added back in quadratic mortality to BWH, RWH and REP, and raised over initial values
 * Working with assimilation efficiency, growth rates and pprey values for benthic groups to get them to persist
 * BWH, REP, and RWH all look reasonable (done)
 - Benthic groups moving in right direction but not done yet.

## Retune Benthic Groups (ATLNTS-155)

  * RG: 12-6-2020
  * Updates to benthic groups: SCA, QHG, CLA, BFF, BG, BC, LOB, RCB, BMS
  * LOB, QHG, BC still crash but much later
  * BG and BFF persist but drop to 1% of starting levels by the end, they still persist at higher values for longer than previously.
  * Zooplankton groups drop to almost nothing by end of run
  
  * Changes in biology file were to mum, clearance rates (for filter feeders) and assimilation efficiency as well as pprey values both for the groups above and the groups that prey on them.
  * Changes in run file were to put the above groups back to an initial conditions multiplier of 1.
