# R script to identify failed Atlantis simulations and generate a new, bundled
# sbatch script to rerun only the failed jobs.

library(stringr)

# --- Configuration ---
# Set the total number of simulation runs you expect
total_runs <- 1:600

# Set the pattern for the SLURM output files.
# This assumes the main job ID was 4 (e.g., "slurm-4_...").
# If your job ID is different, change the "4" in the pattern.
file_pattern <- "slurm-2641_\\d+\\.out"

# Set the root directory where the slurm files are located.
# "." refers to the current directory where you run the script.
search_dir <- "."

# The specific text that indicates a successful run
success_string <- "Free Functional Group memory"

# --- New Configuration for Rerunning ---
# The name of the new sbatch script that will be generated
output_sbatch_file <- here::here('currentVersion','sbatch_eof_targeting_1.sh')

# The number of jobs to partition the failed runs into
num_rerun_jobs <- 6

# --- Main Logic ---
cat("Searching for SLURM output files...\n")
slurm_files <- list.files(path = search_dir, pattern = file_pattern, full.names = TRUE)

if (length(slurm_files) == 0) {
  stop("No SLURM output files found with pattern '", file_pattern, "'. Please check the job ID and directory.")
}

cat("Found", length(slurm_files), "files. Checking for success message...\n")

# Vector to store the IDs of successfully completed runs
successful_ids <- c()

# Loop through each file to check for the success message
for (file in slurm_files) {
  file_content <- tryCatch({
    readLines(file, warn = FALSE)
  }, error = function(e) { character(0) })
  
  if (any(grepl(success_string, file_content, fixed = TRUE))) {
    run_id <- as.numeric(str_extract(basename(file), "(?<=_)\\d+(?=\\.out$)"))
    if (!is.na(run_id)) {
      successful_ids <- c(successful_ids, run_id)
    }
  }
}

# Determine which runs are missing from the successful list
failed_ids <- sort(setdiff(total_runs, successful_ids))

cat("Found", length(successful_ids), "successful runs.\n")
cat("Found", length(failed_ids), "failed or incomplete runs.\n")

# --- Generate the New sbatch Script ---
if (length(failed_ids) > 0) {
  cat("\nGenerating a new sbatch script to rerun failed jobs...\n")
  
  # Partition the failed IDs into chunks for each job
  # Adjust num_rerun_jobs if it's larger than the number of failed jobs
  actual_jobs <- min(num_rerun_jobs, length(failed_ids))
  
  if (actual_jobs < num_rerun_jobs) {
    cat("Warning: Fewer failed jobs than requested rerun jobs. Reducing to", actual_jobs, "jobs.\n")
  }
  
  # Create a list where each element is a vector of IDs for one job
  id_partitions <- split(failed_ids, ceiling(seq_along(failed_ids) / (length(failed_ids) / actual_jobs)))
  names(id_partitions) <- 0:(actual_jobs - 1)
  
  # --- Build the sbatch script content ---
  
  # 1. Header
  sbatch_header <- paste(
    "#!/bin/bash",
    "#SBATCH --job-name=atlantis_rerun_bundle",
    "#SBATCH --partition=compute",
    "#SBATCH --nodes=1",
    "#SBATCH --ntasks-per-node=100", # Request enough CPUs to run in parallel
    "#SBATCH --cpus-per-task=1",
    "#SBATCH --mem-per-cpu=2G",
    paste0("#SBATCH --array=0-", actual_jobs - 1),
    "",
    "# This script was auto-generated by find_failed_runs.R",
    "",
    sep = "\n"
  )
  
  # 2. Case statement to assign simulation IDs to each job
  case_statement <- "case $SLURM_ARRAY_TASK_ID in\n"
  for (i in names(id_partitions)) {
    # Paste IDs together, separated by a space
    id_string <- paste(id_partitions[[i]], collapse = " ")
    case_statement <- paste0(case_statement, "  ", i, ") sim_ids=\"", id_string, "\";;\n")
  }
  case_statement <- paste0(case_statement, "esac\n\n")
  
  # 3. Execution loop
  exec_loop <- paste(
    "echo \"This is array job ${SLURM_ARRAY_TASK_ID}, rerunning simulations: ${sim_ids}\"",
    "",
    "for sim_id in ${sim_ids}; do",
    "    # Use \"&\" to launch each singularity container in the background",
    "    (",
    "        echo \"Starting simulation ${sim_id} on node $(hostname)\"",
    "        output_dir=\"/atlantisoutput/eof_targeting_1/eof_targeting_1_${sim_id}\"",
    "        mkdir -p \"${output_dir}\"",
    "        run_script=\"/app/model/runAtlantis_${sim_id}.sh\"",
    "        singularity exec \\",
    "            --bind /model/Joseph.Caracappa/READ-EDAB-neusAtlantis/currentVersion:/app/model,${output_dir}:/app/model/output \\",
    "            /model/atlantisCode/atlantis6681.sif \\",
    "            ${run_script} &> \"${output_dir}/sim_${sim_id}_rerun.log\"",
    "        echo \"Finished simulation ${sim_id}\"",
    "    ) &",
    "done",
    "",
    "# Wait for all background jobs launched in this script to finish",
    "wait",
    "echo \"All simulations for array job ${SLURM_ARRAY_TASK_ID} are complete.\"",
    sep = "\n"
  )
  
  # Combine all parts and write to the output file
  full_script_content <- paste(sbatch_header, case_statement, exec_loop, sep = "\n")
  writeLines(full_script_content, output_sbatch_file)
  
  cat("Success! New script written to:", output_sbatch_file, "\n")
  cat("You can now run it with: sbatch", output_sbatch_file, "\n")
  
} else {
  cat("\nAll runs completed successfully! No need to rerun.\n")
}

