#Script to create spatial comparisons between any set of runs and some reference file
#Reference file is generated by make_spatial_reference.R
library(atlantisprocessing)
library(dplyr)
## Read in and format reference file


ref.data = readRDS(here::here('data','spatial_reference_survdat_2011_2021.rds'))%>%
  filter(statistic == 'proportion' & var.name == 'biomass')

# ref.data.run = readRDS('/net/work3/EDAB/atlantis/Shared_Data/Dev_Runs/Dev_6681_20240620/Post_Processed/Data/biomass_box.rds')%>%
#   filter(time>30)%>%
#   group_by(species,polygon)%>%
#   summarise(atoutput = mean(atoutput,na.rm=T))%>%
#   group_by(species)%>%
#   mutate(total = sum(atoutput,na.rm=T))%>% 
#   ungroup()%>%
#   mutate(ref.value.run = atoutput/total,
#          var.name = 'biomass',
#          statistic = 'proportion')%>%
#   select(species,polygon,var.name,statistic,ref.value.run)
# 
# ref.data =ref.data %>%
#   left_join(ref.data.run)%>%
#   select(-ref.value)%>%
#   rename(ref.value = 'ref.value.run')

init.data = readRDS(here::here('data','spatial_reference_initial_conditions.rds'))%>%
  filter(statistic == 'proportion' & var.name == 'biomass')

set.prefix = 'SCA_newdist_1_'
run.names = paste0(set.prefix,1:16)

# run.names = c('Dev_6681_20240905','SCA_Dist_1')
# run.dirs = c('/net/work3/EDAB/atlantis/Shared_Data/Dev_Runs/Dev_6681_20240905/',
             # paste0(here::here('Atlantis_Runs','SCA_Dist_1')))
run.dirs = paste0(here::here('Atlantis_Runs',run.names))
run.sets = list(1:4,5:8,9:12,13:16)
j=1

do.processing = T
for(j in 1:length(run.sets)){
  
  run.names.set = run.names[run.sets[[j]]]
  # out.name = paste0(set.prefix,run.sets[[j]][1],'-',run.sets[[j]][length(run.sets[[j]])])
  out.name = paste0(set.prefix,run.sets[[j]][1])
  
  i=1
  for(i in 1:length(run.names.set)){
    run.name = run.names.set[i]
    atl.dir = here::here('Atlantis_Runs',run.name,'')
    param.dir = here::here('currentVersion','/')
    run.prefix = 'neus_output'
    param.ls = get_atl_paramfiles(param.dir,atl.dir,run.prefix = run.prefix,include_catch = T)
    
    if(do.processing){
      process_atl_output(
        param.dir = param.dir,
        atl.dir= atl.dir,
        out.dir = file.path(atl.dir, "/Post_Processed/Data/"),
        run.prefix = run.prefix,
        param.ls = param.ls,
        agg.scale= 'year',
        large.file = F,
        system = 'linux',
        process.all = F,
        plot.all = F,
        plot.benthic = F,
        plot.overall.biomass = F,
        plot.biomass.timeseries = F,
        plot.length.age = F,
        plot.biomass.box = T,
        plot.c.mum = F,
        plot.sn.rn = F,
        plot.recruits = F,
        plot.numbers.timeseries = T,
        plot.physics = F,
        plot.growth.cons = F,
        plot.cohort = F,
        plot.diet = F,
        plot.consumption = F,
        plot.spatial.biomass = F,
        plot.spatial.biomass.seasonal = F,
        plot.catch = F,
        plot.mortality = F,
        plot.weight = F,
        plot.spatial.overlap = F
      )
    }
  }
  ## Run with compare_spatial_vars function from the atlantisprocessing package
  
  atlantisprocessing::compare_spatial_vars(
    
    param.dir = here::here('currentVersion'),
    run.dirs = run.dirs[run.sets[[j]]],
    run.names = run.names.set,
    ref.data = ref.data,
    init.data = init.data,
    out.dir = here::here('Figures','/'),
    out.name = out.name,
    param.ls = get_atl_paramfiles(param.dir = here::here('currentVersion'),
                                  atl.dir = run.dirs[1],
                                  run.prefix = 'neus_output',
                                  include_catch = T
    ),
    data.type = 'proportion',
    comparison.type = 'difference',
    ref.years = 2:4,
    plot =T
  )
  
  
}



atlantisprocessing::compare_spatial_vars(
  
  param.dir = here::here('currentVersion'),
  run.dirs = run.dirs,
  run.names = run.names,
  ref.data = ref.data,
  init.data = init.data,
  out.dir = here::here('Figures','/'),
  out.name = 'SCA_Dist_1',
  param.ls = get_atl_paramfiles(param.dir = here::here('currentVersion'),
                                atl.dir = run.dirs[1],
                                run.prefix = 'neus_output',
                                include_catch = T
  ),
  data.type = 'proportion',
  comparison.type = 'difference',
  ref.years = c(20,60),
  plot =T
)

