#Script to create spatial comparisons between any set of runs and some reference file
#Reference file is generated by make_spatial_refernece.R
library(atlantisprocessing)
library(dplyr)
## Read in and format reference file

ref.data = readRDS(here::here('data','spatial_reference_survdat_2011_2021.rds'))%>%
  filter(statistic == 'proportion' & var.name == 'biomass')

init.data = readRDS(here::here('data','spatial_reference_initial_conditions.rds'))%>%
  filter(statistic == 'proportion' & var.name == 'biomass')

run.names = c('HER_TS_dist_ddepend0',
              'HER_TS_dist_ddepend3')
run.dirs = paste0(here::here('Atlantis_Runs',run.names))

## Run with compare_spatial_vars function from the atlantisprocessing package

atlantisprocessing::compare_spatial_vars(
  
  param.dir = here::here('currentVersion'),
  run.dirs = run.dirs,
  run.names = run.names,
  ref.data = ref.data,
  init.data = init.data,
  out.dir = here::here('Figures/'),
  param.ls = get_atl_paramfiles(param.dir = here::here('currentVersion'),
                                atl.dir = run.dirs[1],
                                run.prefix = 'neus_output',
                                include_catch = T
                                ),
  data.type = 'proportion',
  comparison.type = 'difference',
  ref.years = 45:55,
  plot =T
)


# 
# atlantisprocessing::compare_spatial_vars(
#   
#   param.dir = here::here('currentVersion'),
#   run.dirs = run.dirs,
#   run.names = run.names,
#   ref.data = ref.data.init,
#   out.dir = here::here('Figures','/'),
#   param.ls = get_atl_paramfiles(param.dir = here::here('currentVersion'),
#                                 atl.dir = run.dirs[1],
#                                 run.prefix = 'neus_output',
#                                 include_catch = T
#   ),
#   data.type = 'proportion',
#   comparison.type = 'difference',
#   ref.years = 45:55,
#   plot =T
# )
# 
